GET http://localhost:5000/

###

POST http://localhost:5000/api/auth/login
content-type: application/json

{
    "email": "David",
    "password": "123456"
}

###

POST http://localhost:5000/api/auth/register
content-type: application/json

{
    "email": "email@email.com",
    "password": "123456",
    "role": "admin",
    "name": "Admin"
}

###

POST http://localhost:5000/api/auth/logout

###

GET http://localhost:5000/api/stat/analytics